### ISSUE TITLE
F1 socre is zero when using run_ner.py and run_re to fine tuning bert model

### ISSUE THREAD

**Issue by ayoubharn** [smitkiri/ehr-relation-extraction#1]
When I use run.ner.py and run_re.py scripts, i got F1 score and precision are zero for ner model and re model, I think the problem lies in the format of the training data generated by generate_data right? how do you overcome that?

**Comment by smitkiri** [comment]
Can you share some more details about the steps you performed and a sample output?

**Comment by ayoubharn** [comment]
I followed the steps you have done, first I generated the data by the script generate_data.py for each IE task, and then I trained the model biobert for NER task. At the end of the training I get a file test_result.txt with a score F1 of zero, the same for the file eval_results.txt :

test_result.txt

```
eval_loss = 0.6333050968019458
eval_precision = 0.0
eval_recall = 0.0
eval_f1 = 0.0
```

eval_results.txt:

```
eval_loss = 0.6656930069956515
eval_precision = 0.0
eval_recall = 0.0
eval_f1 = 0.0
epoch = 3.0
```


The biobert model for NER assigns only the tag "O" for the tokens in the file test_predictions.txt

The same for the biobert model for relationship extraction, after generating the data and fine tuning the model biobert for RE, I get a test_result.txt file with an F1 score of zero, the same for the eval_results_ehr-re.txt file :

test_results.txt:
```
f1 score = 0.0
recall = 0.0
precision = 0.0
specificity = 1.0
```
eval_results_ehr-re.txt:
```
eval_results_ehr-re.txt
eval_loss = 0.5521418023042465
eval_acc = 0.7598763697667884
eval_f1 = 0.0
eval_acc_and_f1 = 0.3799381848833942
epoch = 3.0
```
I guess the problem relies in data format train.txt train.tsv .. generated by data_generate.py ?

**Comment by ayoubharn** [comment]
I was having issue with GCP, problem solved thanks!

**Comment by LyaSolis** [comment]
Hi @ayoubharn I am having the same issue in AzureML - how exactly did you resolve it please? Thank you!
