### ISSUE TITLE
Issue with running ner script with only --do predict argument

### ISSUE THREAD

**Issue by yamini7595** [smitkiri/ehr-relation-extraction#13]
The NER model works all fine when I run the ner script with --do train --do predict arguments. 
However, when I just want to find the prediction results and I try to run the script with only --do_predict (without --do_train) using the trained model, I get completely wrong results. 
Is there something small I am missing out?

**Comment by smitkiri** [comment]
Hi Yamini,

Thanks for pointing out the issue. Can you give a few more details on the NER model that you trained and the exact arguments that you use to get the predictions? I can take a look.

**Comment by yamini7595** [comment]
Thank you for the help. 
I used the BIOBERT model for training and the arguments are exactly the same provided in the README. The predictions score is f1 = 0.9814462314997006. 
However, I tested the same command but with some modifications, 
python3 run_ner.py --data_dir ./dataset/ --labels ./dataset/labels.txt --model_name_or_path dmis-lab/biobert-large-cased-v1.1 --output_dir ./output/ --max_seq_length 512 --do_predict --overwrite_output_dir.
And the prediction score f1 = 0.05652248836808547.

**Comment by smitkiri** [comment]
Your `--model_name_or_path` parameter should be the path to your trained model. Using `dmis-lab/biobert-large-cased-v1.1` would take the original pre-trained biobert model.

**Comment by yamini7595** [comment]
Yes , thank you so much for your help.
