### ISSUE TITLE
Train BioBert_ner error, while running run_ner.py (Colab)

### ISSUE THREAD

**Issue by dummynov1** [smitkiri/ehr-relation-extraction#15]
I have installed all the packages as per the requirements.txt file on Colab, including `torch==1.6.0` , `torchvision==0.7.0` , `transformers==3.0.2`

when i run the command  :
`! make train-biobert-ner`

i get the following error : 

cd biobert_ner/ && \
python run_ner.py \
    --data_dir ./dataset/ \
    --labels ./dataset/labels.txt \
    --model_name_or_path dmis-lab/biobert-large-cased-v1.1 \
    --output_dir ./output/ \
    --max_seq_length 128 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 8 \
    --save_steps 4000 \
    --seed 0 \
    --do_train \
    --do_eval \
    --do_predict \
    --overwrite_output_dir
01/31/2022 11:45:17 - INFO - transformers.training_args -   PyTorch: setting up devices
01/31/2022 11:45:17 - WARNING - __main__ -   Process rank: -1, device: cuda:0, n_gpu: 1, distributed training: False, 16-bits training: False
01/31/2022 11:45:17 - INFO - __main__ -   Training/evaluation parameters TrainingArguments(output_dir='./output/', overwrite_output_dir=True, do_train=True, do_eval=True, do_predict=True, evaluate_during_training=False, per_device_train_batch_size=8, per_device_eval_batch_size=8, per_gpu_train_batch_size=None, per_gpu_eval_batch_size=None, gradient_accumulation_steps=1, learning_rate=5e-05, weight_decay=0.0, adam_epsilon=1e-08, max_grad_norm=1.0, num_train_epochs=1.0, max_steps=-1, warmup_steps=0, logging_dir='runs/Jan31_11-45-17_5c9d189f141d', logging_first_step=False, logging_steps=500, save_steps=4000, save_total_limit=None, no_cuda=False, seed=0, fp16=False, fp16_opt_level='O1', local_rank=-1, tpu_num_cores=None, tpu_metrics_debug=False, debug=False, dataloader_drop_last=False, eval_steps=1000, past_index=-1)
01/31/2022 11:45:17 - INFO - transformers.configuration_utils -   loading configuration file https://s3.amazonaws.com/models.huggingface.co/bert/dmis-lab/biobert-large-cased-v1.1/config.json from cache at /root/.cache/torch/transformers/3493610bf2342adb1bf68e2a34c59b725a710eb59df1883605e40ae7e95bf9e4.5b7a692f7cc36e826065fed1096ab38064bca502b90349c26fb1b70aae2defb6
01/31/2022 11:45:17 - INFO - transformers.configuration_utils -   Model config BertConfig {
  "attention_probs_dropout_prob": 0.1,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "id2label": {
    "0": "B-DRUG",
    "1": "I-DRUG",
    "2": "B-STR",
    "3": "I-STR",
    "4": "B-DUR",
    "5": "I-DUR",
    "6": "B-ROU",
    "7": "I-ROU",
    "8": "B-FOR",
    "9": "I-FOR",
    "10": "B-ADE",
    "11": "I-ADE",
    "12": "B-DOS",
    "13": "I-DOS",
    "14": "B-REA",
    "15": "I-REA",
    "16": "B-FRE",
    "17": "I-FRE",
    "18": "O"
  },
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "label2id": {
    "B-ADE": 10,
    "B-DOS": 12,
    "B-DRUG": 0,
    "B-DUR": 4,
    "B-FOR": 8,
    "B-FRE": 16,
    "B-REA": 14,
    "B-ROU": 6,
    "B-STR": 2,
    "I-ADE": 11,
    "I-DOS": 13,
    "I-DRUG": 1,
    "I-DUR": 5,
    "I-FOR": 9,
    "I-FRE": 17,
    "I-REA": 15,
    "I-ROU": 7,
    "I-STR": 3,
    "O": 18
  },
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "pad_token_id": 0,
  "type_vocab_size": 2,
  "vocab_size": 58996
}

01/31/2022 11:45:17 - INFO - transformers.configuration_utils -   loading configuration file https://s3.amazonaws.com/models.huggingface.co/bert/dmis-lab/biobert-large-cased-v1.1/config.json from cache at /root/.cache/torch/transformers/3493610bf2342adb1bf68e2a34c59b725a710eb59df1883605e40ae7e95bf9e4.5b7a692f7cc36e826065fed1096ab38064bca502b90349c26fb1b70aae2defb6
01/31/2022 11:45:17 - INFO - transformers.configuration_utils -   Model config BertConfig {
  "attention_probs_dropout_prob": 0.1,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "pad_token_id": 0,
  "type_vocab_size": 2,
  "vocab_size": 58996
}

01/31/2022 11:45:17 - INFO - transformers.tokenization_utils_base -   Model name 'dmis-lab/biobert-large-cased-v1.1' not found in model shortcut name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased, TurkuNLP/bert-base-finnish-cased-v1, TurkuNLP/bert-base-finnish-uncased-v1, wietsedv/bert-base-dutch-cased). Assuming 'dmis-lab/biobert-large-cased-v1.1' is a path, a model identifier, or url to a directory containing tokenizer files.
01/31/2022 11:45:18 - INFO - transformers.tokenization_utils_base -   loading file https://s3.amazonaws.com/models.huggingface.co/bert/dmis-lab/biobert-large-cased-v1.1/vocab.txt from cache at /root/.cache/torch/transformers/701732fae654e0c36bf4554c7758f748495aa3427b4084607df605f2049a89a0.b2d452d8aee26fe2e337e17013b48f3d5a81bb300c38986450d4022986348bdd
01/31/2022 11:45:18 - INFO - transformers.tokenization_utils_base -   loading file https://s3.amazonaws.com/models.huggingface.co/bert/dmis-lab/biobert-large-cased-v1.1/added_tokens.json from cache at None
01/31/2022 11:45:18 - INFO - transformers.tokenization_utils_base -   loading file https://s3.amazonaws.com/models.huggingface.co/bert/dmis-lab/biobert-large-cased-v1.1/special_tokens_map.json from cache at None
01/31/2022 11:45:18 - INFO - transformers.tokenization_utils_base -   loading file https://s3.amazonaws.com/models.huggingface.co/bert/dmis-lab/biobert-large-cased-v1.1/tokenizer_config.json from cache at None
01/31/2022 11:45:18 - INFO - transformers.tokenization_utils_base -   loading file https://s3.amazonaws.com/models.huggingface.co/bert/dmis-lab/biobert-large-cased-v1.1/tokenizer.json from cache at None
01/31/2022 11:45:18 - INFO - transformers.modeling_utils -   loading weights file https://cdn.huggingface.co/dmis-lab/biobert-large-cased-v1.1/pytorch_model.bin from cache at /root/.cache/torch/transformers/8c1699719a69e0d7cccc2c016217edb876ee6732c3aa2809e15a09c70e9bc22e.2c1d459b35b7f0b1938ff35bf6334bc60282ea79ea7cf7e9656e27f726ed07c6
01/31/2022 11:45:33 - WARNING - transformers.modeling_utils -   Some weights of the model checkpoint at dmis-lab/biobert-large-cased-v1.1 were not used when initializing BertForTokenClassification: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.weight', 'cls.predictions.decoder.bias', 'cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
01/31/2022 11:45:33 - WARNING - transformers.modeling_utils -   Some weights of BertForTokenClassification were not initialized from the model checkpoint at dmis-lab/biobert-large-cased-v1.1 and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
01/31/2022 11:45:33 - INFO - filelock -   Lock 140349564664784 acquired on ./dataset/cached_train_dev_BertTokenizer_128.lock
01/31/2022 11:45:33 - INFO - utils_ner -   Loading features from cached file ./dataset/cached_train_dev_BertTokenizer_128
01/31/2022 11:45:33 - INFO - filelock -   Lock 140349564664784 released on ./dataset/cached_train_dev_BertTokenizer_128.lock
01/31/2022 11:45:33 - INFO - filelock -   Lock 140349564665488 acquired on ./dataset/cached_devel_BertTokenizer_128.lock
01/31/2022 11:45:33 - INFO - utils_ner -   Loading features from cached file ./dataset/cached_devel_BertTokenizer_128
01/31/2022 11:45:33 - INFO - filelock -   Lock 140349564665488 released on ./dataset/cached_devel_BertTokenizer_128.lock
01/31/2022 11:45:35 - INFO - transformers.trainer -   You are instantiating a Trainer but W&B is not installed. To use wandb logging, run `pip install wandb; wandb login` see https://docs.wandb.com/huggingface.
Traceback (most recent call last):
  File "run_ner.py", line 284, in <module>
    main()
  File "run_ner.py", line 206, in main
    model_path=model_args.model_name_or_path if os.path.isdir(model_args.model_name_or_path) else None
  File "/usr/local/lib/python3.7/dist-packages/transformers/trainer.py", line 384, in train
    train_dataloader = self.get_train_dataloader()
  File "/usr/local/lib/python3.7/dist-packages/transformers/trainer.py", line 240, in get_train_dataloader
    if self.args.local_rank == -1
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/sampler.py", line 96, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
Makefile:53: recipe for target 'train-biobert-ner' failed
make: *** [train-biobert-ner] Error 1

**Comment by smitkiri** [comment]
It seems like you do not have the training data configured properly. Did you upload the raw data and generate the training data using `generate_data.py`?

**Comment by dummynov1** [comment]
> It seems like you do not have the training data configured properly. Did you upload the raw data and generate the training data using `generate_data.py`?

May i know from where i can get the raw data to be used for generating training data?

**Comment by dummynov1** [comment]
@smitkiri : I have now realised that you had mentioned in Readme that training data is taken from [n2c2 2018 challenge dataset](https://portal.dbmi.hms.harvard.edu/projects/n2c2-2018-t2/) by creating an account and Raising a request.
Also, how do we get the additional ADE dataset that was used along with above data.?

**Comment by smitkiri** [comment]
You can get them from here: http://lavis.cs.hs-rm.de/storage/spert/public/datasets/ade/

**Comment by dummynov1** [comment]
Thanks for sharing the ADE dataset link.
I'll try training the model on colab. 
While i was also wondering is there a way to save and load the model (make it portable, something similar to model.save(), and model.load(), model.predict() ).?

**Comment by smitkiri** [comment]
Take a look at the parameters of `run_ner.py`. Run `python run_ner.py --help` in a terminal.
