### ISSUE TITLE
ade_corpus format

### ISSUE THREAD

**Issue by robinlin1973** [smitkiri/ehr-relation-extraction#16]
hi,
all the ade_corpus is txt(rel) or csv format, where could I find the json format for generate-data? thanks.

**Comment by smitkiri** [comment]
You can get them from here: http://lavis.cs.hs-rm.de/storage/spert/public/datasets/ade/

**Comment by LyaSolis** [comment]
Hi, 
Thank you for this repo. I was having the same issue as OP trying to figure out required ade corpus format. After reading this thread, I downloaded ade folder from the link you provided, but still having issues...
Code I am running:
`python generate_data.py --task ner --input_dir ../datasets/ --ade_dir ../ade_corpus/ --target_dir biobert_ner/dataset/ --max_seq_len 512 --dev_split 0.1 --tokenizer biobert-base --ext txt --sep " "
`
Folder ../datasets contains train and test subfolders, each has .txt and .ann files in it;  
Folder ../ade_corpus contains all json files from [ttp://lavis.cs.hs-rm.de/storage/spert/public/datasets/ade/](http://lavis.cs.hs-rm.de/storage/spert/public/datasets/ade/) - and yes, there is no index.json file there.... 


`File "generate_data.py", line 225, in <module>
    main()
  File "generate_data.py", line 190, in main
    ade_train_dev = read_ade_data(ade_data_dir=args.ade_dir, verbose=1)
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/lyasolis2/code/Users/lyasolis/ehr-relation-extraction/utils.py", line 338, in read_ade_data
    with open(ade_data_dir + fid + '.json') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../ade_corpus/index.json'`
