### ISSUE TITLE
How to get the n2c2 data in TSV format?

### ISSUE THREAD

**Issue by xegulon** [smitkiri/ehr-relation-extraction#2]
Hi,

I see in the code ([this file](https://github.com/smitkiri/ehr-relation-extraction/blob/master/generate_data.py)) that to generate the data for RE, one needs to have the dataset as TSV files.

However, as far as I know, the n2c2 2018 dataset is provided as BRAT files (I asked for it).

Am I wrong, or is there a script that makes the conversion from BRAT to the TSV format you use?

**Comment by smitkiri** [comment]
Hey, 
You need to get the n2c2 2018 task 2 dataset which is a bunch of *.txt and *.ann files. The **output** of the RE generator is tsv files, the inputs are txt and ann files ([you can see the code for that here](https://github.com/smitkiri/ehr-relation-extraction/blob/master/biobert_re/utils_re.py#L233)).
