### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by LyaSolis** [smitkiri/ehr-relation-extraction#21]
Hi Smit, 

I trained NER model using your repo + added some custom data. When I run predictions on custom dataset, it works fine on most files, but about 20% of files get the following error:

```
Prediction: 100%
1/1 [00:00<00:00, 4.22it/s]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-33-ad82028bb83c>](https://localhost:8080/#) in <module>()
----> 1 ner_predictions = get_ner_predictions(ehr_record=text, model_name="biobert")
      2 text_ner = ner_predictions.get_entities()

2 frames
[/content/ehr.py](https://localhost:8080/#) in get_char_idx(self, token_idx)
    319             raise AttributeError("Tokenizer not set.")
    320 
--> 321         char_idx = self.token_to_char_map[token_idx]
    322 
    323         return char_idx

IndexError: list index out of range
```
Would you know where the issue might be, please?
Thank you!

**Comment by smitkiri** [comment]
I think I might've seen this before. Can you paste the detailed error here? The 2 frames between the entry point and the error are hidden here

**Comment by LyaSolis** [comment]
Thanks @smitkiri ! 

Here is a full error print out:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-9-0646245b0df3>](https://localhost:8080/#) in <module>()
----> 1 ner_predictions = get_ner_predictions(ehr_record=txt, model_name="biobert")
      2 text_ner = ner_predictions.get_entities()

3 frames
[/content/predict.py](https://localhost:8080/#) in get_ner_predictions(ehr_record, model_name, record_id)
    267                                 tokenizer=biobert_ner_tokenizer.tokenize,
    268                                 is_bert_tokenizer=True,
--> 269                                 is_training=False)
    270 
    271         predictions = get_biobert_ner_predictions(test_ehr)

[/content/ehr.py](https://localhost:8080/#) in __init__(self, record_id, text_path, ann_path, text, tokenizer, is_bert_tokenizer, is_training)
     66         self.is_bert_tokenizer = is_bert_tokenizer
     67         self.elmo = None
---> 68         self.set_tokenizer(tokenizer)
     69         self.split_idx = None
     70 

[/content/ehr.py](https://localhost:8080/#) in set_tokenizer(self, tokenizer)
    278         self.tokenizer = tokenizer
    279         if tokenizer is not None:
--> 280             self._compute_tokens()
    281 
    282     def get_token_idx(self, char_idx: int) -> int:

[/content/ehr.py](https://localhost:8080/#) in _compute_tokens(self)
    217             # Characters that are discarded from tokenization
    218             while self.text[j].lower() != self.tokens[i][k].lower():
--> 219                 char_to_token_map.append(char_to_token_map[-1])
    220                 j += 1
    221 

IndexError: list index out of range
```
I have been googling this, and tried different suggestions, but neither fixed it (like setting model and tokenizer vocal len, not using FastTokenizer etc).

**Comment by LyaSolis** [comment]
Also just tried to generate dataset on new files and am getting the same error...
```
Progress: [===================>] 201/202./data/n2c2_2018_LAG/test/157103.ann
Progress: [====================] 202/202

ADE data: Done


Traceback (most recent call last):
  File "generate_data.py", line 229, in <module>
    main()
  File "generate_data.py", line 217, in main
    ner_generator(files, args)
  File "generate_data.py", line 97, in ner_generator
    generate_input_files(ehr_records=data[0], ade_records=data[1],
  File "/Users/lsolis/Documents/GitHub/PAH_publications/ehr/ehr-ner/train_model_v3/biobert_ner/utils_ner.py", line 333, in generate_input_files
    labels = record.get_labels()
  File "/Users/lsolis/Documents/GitHub/PAH_publications/ehr/ehr-ner/train_model_v3/ehr.py", line 348, in get_labels
    start_idx = self.get_token_idx(ent.range[0])
  File "/Users/lsolis/Documents/GitHub/PAH_publications/ehr/ehr-ner/train_model_v3/ehr.py", line 299, in get_token_idx
    token_idx = self.char_to_token_map[char_idx]
IndexError: list index out of range
```

**Comment by smitkiri** [comment]
> Thanks @smitkiri !
> 
> Here is a full error print out:
> 
> ```
> ---------------------------------------------------------------------------
> IndexError                                Traceback (most recent call last)
> [<ipython-input-9-0646245b0df3>](https://localhost:8080/#) in <module>()
> ----> 1 ner_predictions = get_ner_predictions(ehr_record=txt, model_name="biobert")
>       2 text_ner = ner_predictions.get_entities()
> 
> 3 frames
> [/content/predict.py](https://localhost:8080/#) in get_ner_predictions(ehr_record, model_name, record_id)
>     267                                 tokenizer=biobert_ner_tokenizer.tokenize,
>     268                                 is_bert_tokenizer=True,
> --> 269                                 is_training=False)
>     270 
>     271         predictions = get_biobert_ner_predictions(test_ehr)
> 
> [/content/ehr.py](https://localhost:8080/#) in __init__(self, record_id, text_path, ann_path, text, tokenizer, is_bert_tokenizer, is_training)
>      66         self.is_bert_tokenizer = is_bert_tokenizer
>      67         self.elmo = None
> ---> 68         self.set_tokenizer(tokenizer)
>      69         self.split_idx = None
>      70 
> 
> [/content/ehr.py](https://localhost:8080/#) in set_tokenizer(self, tokenizer)
>     278         self.tokenizer = tokenizer
>     279         if tokenizer is not None:
> --> 280             self._compute_tokens()
>     281 
>     282     def get_token_idx(self, char_idx: int) -> int:
> 
> [/content/ehr.py](https://localhost:8080/#) in _compute_tokens(self)
>     217             # Characters that are discarded from tokenization
>     218             while self.text[j].lower() != self.tokens[i][k].lower():
> --> 219                 char_to_token_map.append(char_to_token_map[-1])
>     220                 j += 1
>     221 
> 
> IndexError: list index out of range
> ```
> 
> I have been googling this, and tried different suggestions, but neither fixed it (like setting model and tokenizer vocal len, not using FastTokenizer etc).



Okay so this is what's happening here: The value of `text[j]` (where I'm pretty sure `j==0`) doesn't match the value of `tokens[i][k]` (again, I'm pretty sure `i==0`, you can double check that by printing them out). You can print out the value of `text[j:j+10]` and `tokens[i]` to see if something's weird. My guess is that the text starts with `##`? Let me know if that's the case. 

If not, can you tell me the values of `text`, `tokens`, `i`, `j`, `k`. Sorry this error might require a lot of hands-on debugging, I might ask you for a bunch of different things

**Comment by smitkiri** [comment]
Closing this since it's been inactive for a while. Feel free to re-open this if you still face any issues.
