### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Taghreed7878** [smitkiri/ehr-relation-extraction#22]
Is data available to get?

**Comment by smitkiri** [comment]
The data is available here: https://portal.dbmi.hms.harvard.edu/projects/n2c2-nlp/

I had to send in a request to access, not sure if that's changed now

**Comment by Taghreed7878** [comment]
I got the data but I'm not sure if it's annotated or just the texts are available.

**Comment by smitkiri** [comment]
It should be annotated

**Comment by Taghreed7878** [comment]
Thanks
