### ISSUE TITLE
List index out of range while running re

### ISSUE THREAD

**Issue by FardinAhsanSakib** [smitkiri/ehr-relation-extraction#23]
WARNING:__main__:Process rank: -1, device: cpu, n_gpu: 0, distributed training: False, 16-bits training: False
Traceback (most recent call last):
  File "run_re.py", line 230, in <module>
    main()
  File "run_re.py", line 103, in main
    REDataset(data_args, tokenizer=tokenizer, cache_dir=model_args.cache_dir) if training_args.do_train else None
  File "/content/ehr-relation-extraction/biobert_re/utils_re.py", line 129, in __init__
    examples = self.processor.get_train_examples(args.data_dir)
  File "/content/ehr-relation-extraction/biobert_re/data_processor.py", line 116, in get_train_examples
    return self._create_examples(self._read_tsv(os.path.join(data_dir, "train.tsv")), "train")
  File "/content/ehr-relation-extraction/biobert_re/data_processor.py", line 139, in _create_examples
    label = None if set_type == "test" else line[1]
IndexError: list index out of range

**Comment by smitkiri** [comment]
Closing since this was resolved on email - there was a problem with the dataset. It has to be in tsv format (tab separated, not comma separated)

**Comment by vedants03** [comment]
Can you please help me, I am facing the same problem?

**Comment by smitkiri** [comment]
@vedants03 Did you check your data files to make sure they're tab separated and not comma separated?

**Comment by vedants03** [comment]
@smitkiri thanks for your reply, I used generate_data.py file for generating .tsv files for training of model. How do I make sure these files are in proper tsv format?

**Comment by vedants03** [comment]
@smitkiri thanks for reply, as you mentioned I checked my datafiles and they were in csv format, I fixed the same and it worked for me. Thanks for helping !!
