### ISSUE TITLE
Getting zero results on running evaluation script

### ISSUE THREAD

**Issue by vedants03** [smitkiri/ehr-relation-extraction#27]
Hi there, I ran the [Track2-evaluate-ver4.py](https://github.com/smitkiri/ehr-relation-extraction/blob/master/Track2-evaluate-ver4.py) file on the gold standard test data and the test data(track 2) from n2c2 and I am getting zero scores on Relations for every entity. Please find the output of the execution below

****************************** TRACK 2 *******************************
                      ------- strict -------    ------ lenient -------
                      Prec.   Rec.    F(b=1)    Prec.   Rec.    F(b=1)
                Drug  0.9990  0.9997  0.9993    0.9990  0.9997  0.9993
            Strength  1.0000  1.0000  1.0000    1.0000  1.0000  1.0000
            Duration  0.9947  1.0000  0.9974    0.9947  1.0000  0.9974
               Route  1.0000  1.0000  1.0000    1.0000  1.0000  1.0000
                Form  0.9998  0.9995  0.9997    1.0000  0.9998  0.9999
                 Ade  0.9968  0.9968  0.9968    0.9968  0.9968  0.9968
              Dosage  0.9996  0.9996  0.9996    0.9996  0.9996  0.9996
              Reason  0.9945  1.0000  0.9973    0.9945  1.0000  0.9973
           Frequency  0.9988  0.9995  0.9991    0.9995  1.0000  0.9998
                      ------------------------------------------------
     Overall (micro)  0.9989  0.9997  0.9993    0.9990  0.9998  0.9994
     Overall (macro)  0.9990  0.9997  0.9993    0.9991  0.9997  0.9994

***************************** RELATIONS ******************************
    Strength -> Drug  0.0000  0.0000  0.0000    0.0000  0.0000  0.0000
      Dosage -> Drug  0.0000  0.0000  0.0000    0.0000  0.0000  0.0000
    Duration -> Drug  0.0000  0.0000  0.0000    0.0000  0.0000  0.0000
   Frequency -> Drug  0.0000  0.0000  0.0000    0.0000  0.0000  0.0000
        Form -> Drug  0.0000  0.0000  0.0000    0.0000  0.0000  0.0000
       Route -> Drug  0.0000  0.0000  0.0000    0.0000  0.0000  0.0000
      Reason -> Drug  0.0000  0.0000  0.0000    0.0000  0.0000  0.0000
         ADE -> Drug  0.0000  0.0000  0.0000    0.0000  0.0000  0.0000
                      ------------------------------------------------
     Overall (micro)  0.0000  0.0000  0.0000    0.0000  0.0000  0.0000
     Overall (macro)  0.0000  0.0000  0.0000    0.0000  0.0000  0.0000
     
This is the output I am getting and I am confused what's wrong here. Also when I ran run_re.py, I am getting ZeroDivision error as mentioned [here](https://github.com/smitkiri/ehr-relation-extraction/issues/8) and now I am wondering whether these two have any relation and causing error in the training of model. 
It would mean a lot if you can help me regarding this or point out if I am doing something wrong here.

**Comment by smitkiri** [comment]
Yeah it looks like the model isn't being trained correctly. You might need to look at the variables of train / val datasets and see if those make sense and they look like you expect them to

**Comment by vedants03** [comment]
Thanks for the reply,
I checked the datasets and train and dev sets appears to be fine. But when I looked at the test_labels.tsv all the sentences have label as 0 and when I ran the predictions on test dataset the model is predicting label 1 for all the indexes(sentences). I think the test_lables.tsv file is not generated properly but I can't find a solution for it. Can you please help me?

**Comment by summer3shadow** [comment]
> Thanks for the reply, I checked the datasets and train and dev sets appears to be fine. But when I looked at the test_labels.tsv all the sentences have label as 0 and when I ran the predictions on test dataset the model is predicting label 1 for all the indexes(sentences). I think the test_lables.tsv file is not generated properly but I can't find a solution for it. Can you please help me?

Did you resolve this problem? @vedants03 @smitkiri

**Comment by vedants03** [comment]
> > Thanks for the reply, I checked the datasets and train and dev sets appears to be fine. But when I looked at the test_labels.tsv all the sentences have label as 0 and when I ran the predictions on test dataset the model is predicting label 1 for all the indexes(sentences). I think the test_lables.tsv file is not generated properly but I can't find a solution for it. Can you please help me?
> 
> Did you resolve this problem? @vedants03 @smitkiri

Yes just make sure you are using the correct extension and separator while using the generate_data.py file for relationship extraction task. Regarding the ZeroDivisionError the error, in my case was due to high learning rate parameter so you can adjust it according to your system and after that training of model works fine. Also, what I observed was, that I was not getting desired evaluation results for the trained Relationship Extraction model and after analysing a bit I came to conclusion that model is trained correclty but the testing dataset used is slightly imbalanced so I used RapidMiner for further balancing the dataset.
