### ISSUE TITLE
BertTokenizer lock file not found

### ISSUE THREAD

**Issue by xegulon** [smitkiri/ehr-relation-extraction#3]
When I run the RE training, I get this error:

```bash
FileNotFoundError: [Errno 2] No such file or directory: './dataset/cached_train_BertTokenizer_128_ehr-re.lock'
```

How can I solve it?

**Comment by smitkiri** [comment]
Based on [this issue](https://github.com/huggingface/transformers/issues/8959) on transformers, there might be some typo in your config

**Comment by xegulon** [comment]
Thanks, I solved my issue. I had to do `export DATA_DIR=../dataset` instead of `export DATA_DIR=./dataset`.

**Comment by Bharathi-A-7** [comment]
@smitkiri could you please help me with [this issue](https://github.com/huggingface/transformers/issues/15850)?

**Comment by TotalBaliw** [comment]
kindly help me i am facing the error too.
 FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Indoo/.cache\\huggingface\\hub\\models--openai--clip-vit-large-patch14\\snapshots\\32bd64288804d66eefd0ccbe215aa642df71cc41\\tokenizer_config.json'
