### ISSUE TITLE
How to use the relation extraction model for inference?

### ISSUE THREAD

**Issue by xegulon** [smitkiri/ehr-relation-extraction#4]
Everything is in the title.

After having run `run_re.py`, how to use it for RE predictions with new data? 

Do the new data need to have its entities annotated?

**Comment by smitkiri** [comment]
The inference code is in [predict.py](https://github.com/smitkiri/ehr-relation-extraction/blob/master/predict.py) file

**Comment by xegulon** [comment]
Ok thanks!
